### ISSUE TITLE
error when importing mumpy

### ISSUE THREAD

**Issue by adauphin** [basnijholt/mumpy#1]
In [1]: import mumpy.mumps as mumps
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-b841dd8d5c24> in <module>()
Hello,

I get an error when I import mumpy. Do you know what could be the origin of the issue?

Thanks!

Alexandre

============================

----> 1 import mumpy.mumps as mumps

~/anaconda/lib/python3.5/site-packages/mumpy/mumps.py in <module>()
     16 import scipy.sparse
     17 import warnings
---> 18 from . import _mumps
     19 from .fortran_helpers import prepare_for_fortran
     20 

ImportError: dlopen(/Users/myuser/anaconda/lib/python3.5/site-packages/mumpy/_mumps.cpython-35m-darwin.so, 2): Symbol not found: _zmumps_c
  Referenced from: /Users/myuser/anaconda/lib/python3.5/site-packages/mumpy/_mumps.cpython-35m-darwin.so
  Expected in: flat namespace
 in /Users/myuser/anaconda/lib/python3.5/site-packages/mumpy/_mumps.cpython-35m-darwin.so

**Comment by basnijholt** [comment]
Hi Alexandre,

Thanks for your interest in using `mumpy`, this version of mumps is only able to handle complex numbers.

We (me and my colleagues) are continuing the development [here](https://gitlab.kwant-project.org/kwant/mumpy).

**Comment by slavoutich** [comment]
I should add, that the repo seems to be still private, so that link won't work. But we hope to release soon :)

**Comment by adauphin** [comment]
Hi guys, thank you for the answer. 

Actually, the problem already appears when I import the mumpy package.

**Comment by dubzeleniy** [comment]
Hi I am also getting an import error below. "import mumpy" by itself works.

>>> import mumpy.mumps
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/<user>/mumpy/mumpy/mumps.py", line 18, in <module>
    from . import _mumps
ImportError: cannot import name '_mumps' from 'mumpy' (/home/<user>/mumpy/mumpy/__init__.py)
